server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:cryptodb
    driverClassName: org.h2.Driver
    username: sa
    password: supersecret
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: validate
  flyway:
    enabled: true
    locations: classpath:db/migration
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
  h2:
    console:
      enabled: true